Repository openshift/openshift-client-python, pull requests merged in 2019-06, with the labels that each got.

#26 Make ListModel can_match consistent with subset style check
  jobs/ci/pr.groovy
  packages/openshift/model.py
  packages/openshift/test_model.py
  run_unittests.sh
Labels: size/M

#28 adding function to get numerical value from units
  packages/openshift/test_util.py
  packages/openshift/util.py
Labels: size/M

#27 Adding missing title in readme.md file.
  readme.md
Labels: size/XS

#29 Do not update kubeconfig on new-project
  packages/openshift/base_verbs.py
Labels: size/S
