Repository openshift/openshift-client-python, pull requests merged in 2019-05, with the labels that each got.

#7 Improving redaction
  packages/openshift/action.py
Labels: size/M

#15 Adding timeout context to actions
  packages/openshift/action.py
  packages/openshift/context.py
  packages/openshift/result.py
Labels: size/L

#16 Fixing casing in pod build code
  packages/openshift/base_verbs.py
Labels: size/S

#18 Add failure tolerations to until_ functions
  packages/openshift/selector.py
Labels: size/M

#20 Setup Prerequisites
  readme.md
Labels: size/S

#21 Add client_host information to action
  packages/openshift/action.py
Labels: size/M

#22 Implementing limit to actions for tracking
  packages/openshift/context.py
  packages/openshift/result.py
Labels: size/S

#24 Additional kubeconfig apis
  packages/openshift/config.py
Labels: size/M
