Repository openshift/openshift-client-python, pull requests merged in 2019-07, with the labels that each got.

#31 Fix local execution to use UTF-8
  packages/openshift/action.py
  packages/openshift/util.py
Labels: size/S

#32 Fix local invoke tempfile & resourceVersion
  examples/cluster_tests.py
  packages/openshift/action.py
  packages/openshift/apiobject.py
  packages/openshift/base_verbs.py
  packages/openshift/util.py
Labels: size/L

#33 sa token extract and ansible update
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  ansible/roles/openshift_client_python/meta/main.yml
  ansible/roles/openshift_client_python/readme.md
  ansible/roles/openshift_client_python/tasks/main.yml
  ansible/roles/openshift_python/readme.md
  ansible/run_sample_playbook.sh
  ansible/sample_playbook.yml
  packages/openshift/base_verbs.py
Labels: size/L

#34 Improve ansible support
  ansible/module_utils/openshift
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  ansible/roles/openshift_client_python/module_utils/openshift
  ansible/roles/openshift_client_python/readme.md
  ansible/run_sample_playbook.sh
  ansible/sample_playbook.yml
  packages/openshift/__init__.py
  packages/openshift/ansible.py
Labels: size/L

#35 Adding subset
  packages/openshift/apiobject.py
  packages/openshift/selector.py
Labels: size/M

#36 Porting Stage1 changes
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  examples/cluster_tests.py
  examples/coverage.py
  examples/simple.py
  lambda/model/python/model.py
  packages/monitoring.py
  packages/openshift/__init__.py
  packages/openshift/apiobject.py
  packages/openshift/base_verbs.py
  packages/openshift/model.py
  packages/openshift/result.py
  packages/openshift/selector.py
  packages/openshift/util.py
Labels: size/L

#37 Fix ansible module to support python3
  .gitattributes
  ansible/rebuild_module.sh
  ansible/roles/__init__.py
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  ansible/roles/openshift_client_python/library/openshift_client_python.template.py
  ansible/roles/openshift_client_python/module_utils/openshift
  jobs/ci/pr.groovy
Labels: size/L

#38 Enable rebuild_module check
  ansible/rebuild_module.digest
  ansible/rebuild_module.sh
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  jobs/ci/pr.groovy
  packages/openshift/__init__.py
Labels: size/S

#39 Cleanup extracted module
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  ansible/roles/openshift_client_python/library/openshift_client_python.template.py
  ansible/run_sample_playbook.sh
  ansible/sample_playbook.yml
Labels: size/M

#41 Porting Stage 2 - verify runs successfully
  ansible/rebuild_module.digest
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  examples/cluster_tests.py
  examples/coverage.py
  examples/dump.py
  examples/report.py
  examples/simple.py
  lambda/model/python/model.py
  packages/monitoring.py
  packages/openshift/__init__.py
  packages/openshift/action.py
  packages/openshift/ansible.py
  packages/openshift/apiobject.py
  packages/openshift/base_verbs.py
  packages/openshift/config.py
  packages/openshift/context.py
  packages/openshift/model.py
  packages/openshift/naming.py
  packages/openshift/result.py
  packages/openshift/selector.py
  packages/openshift/status.py
  packages/openshift/test_model.py
  packages/openshift/test_selector.py
  packages/openshift/test_util.py
  packages/openshift/util.py
Labels: size/L

#42 Revert "Porting Stage 2 - verify runs successfully"
  ansible/rebuild_module.digest
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  examples/cluster_tests.py
  examples/coverage.py
  examples/dump.py
  examples/report.py
  examples/simple.py
  lambda/model/python/model.py
  packages/monitoring.py
  packages/openshift/__init__.py
  packages/openshift/action.py
  packages/openshift/ansible.py
  packages/openshift/apiobject.py
  packages/openshift/base_verbs.py
  packages/openshift/config.py
  packages/openshift/context.py
  packages/openshift/model.py
  packages/openshift/naming.py
  packages/openshift/result.py
  packages/openshift/selector.py
  packages/openshift/status.py
  packages/openshift/test_model.py
  packages/openshift/test_selector.py
  packages/openshift/test_util.py
  packages/openshift/util.py
Labels: size/L

#43 Porting via modernize -- verify works
  ansible/rebuild_module.digest
  ansible/roles/openshift_client_python/library/openshift_client_python.py
  ansible/roles/openshift_client_python/library/openshift_client_python.template.py
  examples/cluster_tests.py
  examples/coverage.py
  examples/dump.py
  examples/report.py
  examples/simple.py
  lambda/model/python/model.py
  packages/monitoring.py
  packages/openshift/action.py
  packages/openshift/ansible.py
  packages/openshift/apiobject.py
  packages/openshift/base_verbs.py
  packages/openshift/config.py
  packages/openshift/context.py
  packages/openshift/model.py
  packages/openshift/naming.py
  packages/openshift/selector.py
  packages/openshift/status.py
  packages/openshift/test_model.py
  packages/openshift/test_selector.py
  packages/openshift/test_util.py
  packages/openshift/util.py
Labels: size/L
